server:
  port: 8082
  servlet:
    context-path: /
  tomcat:
    accesslog:
      buffered: true
      directory: /home/log/tomcat
      enabled: true
      file-date-format: .yyyy-MM-dd
      pattern: '%t | %{X-Real-IP}i | %b | %B | %H | %l | %m | %p | %q | %r | %s | %S | %u | %U | %v | %D | %T | %{Cookie}i | %{User-Agent}i | %{a}r'
      prefix: access_log
      rename-on-rotate: false
      request-attributes-enabled: false
      rotate: true
      suffix: .log
spring:
  application:
    name: support
  datasource:
    name: test
    url: jdbc:mysql://localhost:3306/game?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: 10086
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapper/*/*.xml
  type-aliases-package: com.game.www
logging:
  config: classpath:logback-spring.xml

